owner: mdasifj625
repo: upptime # The name of this repository

sites:
  - name: TarbiyahOS Website
    url: https://tarbiyahos.com

  - name: API Health
    url: https://tarbiyahos.com/api/health

status-website:
  cname: uptime.tarbiyahos.com
  logoUrl: https://tarbiyahos.com/images/logo.png
  name: TarbiyahOS Uptime
  introTitle: "Welcome to TarbiyahOS Uptime"
  introMessage: Service availability and uptime monitoring.
  navbar:
    - title: Status
      href: /

    - title: Main Website
      href: https://tarbiyahos.com

    - title: Blog
      href: https://tarbiyahos.com/blog

    - title: App (PWA)
      href: https://tarbiyahos.com/app
